Upgrade to phpunit 9 and drop php 7.2 support
phpDocumentor/ReflectionCommon pull request #33
Opened 2020-10-04 02:50 UTC by DIOHz0r

Changes to solve issue #32

2020-10-04 11:56 UTC, jaapio commented on composer.json
> +        "phpunit/phpunit": "^9.1"
phpunit cannot be installed via composer, it will lead to issues because this library is a dependency of phpunit. Could you please update the phive config to bump to phpunit 9.1.

2020-10-04 11:57 UTC, jaapio requested changes
Thanks for your PR, 

I added a small comment about phpunit, and our pipeline has detected an issue. Could you please have a look at those changes?

2020-10-05 22:06 UTC, DIOHz0r commented
Hello, finally all fixes where applied

2020-10-06 06:12 UTC, merged

2020-10-06 06:13 UTC, jaapio commented
Thanks!